### ISSUE TITLE
Error : Request code was : 0 for basic history api kotlin

### ISSUE THREAD

**Issue by ummeSuleyath** [android/fit-samples#51]
Hi, 
I have followed the all the steps to configure this app but every time i get this error and  the same steps were followed for different sample apps it seems to work fine except for BasicHistoryApi

E/BasicHistoryApi: There was an error signing into Fit. Check the troubleshooting section of the README
    for potential issues.
    Request code was: 0
    Result code was: 0

**Comment by ellasaro** [comment]
Found a solution?

**Comment by Aurangempire** [comment]
+1

**Comment by retroZap** [comment]
For anyone with the a similar issue for me the issue was fixed as I added my google account at test users at the OAuth consent screen.

Step by step:

1. OAuth consent screen
2. OAuth user cap
3. Test users
4. Click on "Add Users button"
5. Add active Google account

This link helped me solve the problem. In case it is more complex for someone else !

https://stackoverflow.com/questions/67586876/google-fit-authorization-auth-denied-authorization-cancelled

**Comment by teraiyamayurcontact** [comment]
i am also facing same issue. And my project scope is also approved but still facing same issue.
